#%RAML 1.0 SecurityScheme

description: This scheme validates request by using a token
type: x-custom
displayName: Bearer
describedBy:
  headers:
    Authorization:
      description: The header should contain a valid token
      type: string