#%RAML 1.0
title: American Flights System API

types:
    AmericanFlight: !include types/AmericanFlightDataType.raml
traits:
  errorTraits: !include traits/errorTraits.raml

/flights:
    description: Resource represents a collection of flights.
    get:
        description: Retrieve a list of flights based on optional query parameters.
        is: [errorTraits]
        queryParameters:
            destination:
                description: Filter flights by destination
                required: false
                enum:
                    - SFO
                    - LAX
                    - CLE
        responses:
            200:
                body:
                    application/json:
                        type: AmericanFlight[]
                        examples:
                            output: !include  examples/AmericanFlightsExample.raml
            
    post:
        description: Create a new flight.
        is: [errorTraits]
        body:
            application/json:
                type: AmericanFlight
                examples:
                    input: !include examples/AmericanFlightNoIDExample.raml
        responses:
            201:
                body:
                    application/json:
                        example:
                            message: Flight successfully created

    /{ID}:
        description: Resource represents an individual flight identified by its unique ID.
        get:
            description: Retrieve details for a specific flight identified by the provided ID.
            is: [errorTraits]
            responses:
                200:
                    body:
                        application/json:
                            type: AmericanFlight
                            examples:
                                output: !include examples/AmericanFlightExample.raml
