#%RAML 1.0 NamedExample
value:
  - 
    ID: 1
    code: rree0001
    price: 541.99
    departureDate: 2023-12-20
    origin: MUA
    destination: LAX
    emptySeats: 0
    plane:
      type: Boeing 787
      totalSeats: 200
  - 
    ID: 2 
    code: eefd0123
    price: 300.99
    departureDate: 2023-12-20
    origin: MUA
    destination: CLE
    emptySeats: 7
    plane: 
      type: Boeing 747
      totalSeats: 345
